backtest:
  benchmark: '000300'
  commission: 0.0003
  end_date: '2024-12-31'
  initial_capital: 1000000
  slippage: 0.001
  start_date: '2022-01-01'
data_source:
  etf_list_file: data/raw/etf_list.csv
  provider: akshare
database:
  database: quant_db
  host: localhost
  password: '12345678'
  port: 3306
  type: mysql
  username: root
logging:
  level: INFO
  log_file: logs/quant_{date}.log
  log_to_file: true
strategy:
  risk_control:
    initial_stop_loss_atr_multiple: 2.0
    max_daily_loss_percentage: 0.02
    max_industry_exposure: 5
    position_sizing_method: kelly
    trailing_stop_percentage: 0.03
  rotation:
    lookback_period: 5
    top_n_industries: 3
  trend:
    bollinger_period: 20
    bollinger_std_dev: 2.0
    ema_channel_period: 144
    ema_channel_width: 0.05
    ema_long_period: 200
    ema_short_period: 21
    fast_ma: 5
    signal_weights:
      bb_signal: 1.0
      ema_reversal_signal: 1.2
      ema_signal: 1.5
      multi_timeframe_signal: 2.0
      volume_price_signal: 0.8
    slow_ma: 10
    timeframes:
    - 5
    - 10
    - 20
    volume_threshold: 1.2
trading:
  final_check_time: '14:50'
  schedule_time: '14:00'
visualization:
  output_format: png
  plot_drawdown: true
  plot_equity_curve: true
  plot_trade_signals: true
